name: Test

on:
  push:
    branches: [ubuntu-24-amd64, main]
  pull_request:
    branches: [ubuntu-24-amd64, main]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: make test-only
